ARG PG_VERSION=17
ARG PYTHON_VERSION=3

# --------------------------------------------- base1
FROM packpack/packpack:astra-1.7 AS base1

RUN apt update
RUN apt install -y sudo curl ca-certificates
RUN apt update
RUN apt install -y openssh-server
RUN apt install -y time
# RUN apt install -y netcat-traditional

RUN apt install -y git

# --------------------------------------------- postgres
FROM base1 AS base1_with_dev_tools

# --------------------------------------------- base2_with_python-3
FROM base1_with_dev_tools AS base2_with_python-3
RUN apt install -y python3 python3-dev python3-venv

ENV PYTHON_BINARY=python3

# --------------------------------------------- final
FROM base2_with_python-${PYTHON_VERSION} AS final

RUN useradd -m test

ADD --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres
RUN mkdir /home/test/testgres/logs
RUN chown -R test:test /home/test/testgres/logs

ENV LANG=C.UTF-8

USER test

ENTRYPOINT sh -c " \
set -eux; \
bash run_tests3.sh;"
